//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlosClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Score
    {
        public int Score_Id { get; set; }
        public int Measurement_ID { get; set; }
        public decimal Score_Val { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Measurement Measurement { get; set; }
    }
}
